# Generated by Django 5.2 on 2025-04-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='care',
            field=models.TextField(null=True),
        ),
    ]
